//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace prjFinalProject3.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class TableMembers1081747
    {
        [DisplayName("會員編號")]
        [Required(ErrorMessage = "會員編號不可空白")]
        public int MemId { get; set; }

        [DisplayName("姓名")]
        [Required(ErrorMessage = "姓名不可空白")]
        public string MemName { get; set; }

        [DisplayName("姓別")]
        public string MemGender { get; set; }

        [DisplayName("電話")]
        public string MemPhone { get; set; }

        [DisplayName("信箱")]
        [EmailAddress(ErrorMessage = "Email格式有誤")]
        public string MemEmail { get; set; }

        [DisplayName("入會日期")]
        [DataType(DataType.Date, ErrorMessage = "入會日期必須為日期格式")]
        public Nullable<System.DateTime> MemJoinDate { get; set; }

        [DisplayName("餘額")]
        [Range(0, 10000, ErrorMessage = "餘額必須介於0~10000")]
        public Nullable<double> MemBalence { get; set; }

        [DisplayName("體重")]
        public Nullable<double> MemWeight { get; set; }

        [DisplayName("身高")]
        public Nullable<double> MemHeight { get; set; }
    }
}
